<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_K2 Sewing Plant</name>
   <tag></tag>
   <elementGuidId>a7b530e1-d128-4186-893e-ebb88f5ceae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='mat-option-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>b3642a09-223e-4f45-9e53-40ebc8913c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ee9fcae8-e551-492c-a7e7-a7f5ae790a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-option mdc-list-item mdc-list-item--selected mat-mdc-option-active ng-tns-c1073613477-2 ng-star-inserted</value>
      <webElementGuid>9d85f14f-87d9-49ef-9bf6-ae9aed5e8aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-4</value>
      <webElementGuid>0b543771-4432-4b97-91a6-ec89df91d5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87dbe195-761c-4c15-a720-b5825ea8f4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccac8137-287b-4ee3-8ee9-fa07fbd04a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K2 Sewing Plant</value>
      <webElementGuid>d966f941-9132-44d4-b6e1-95806888e8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-4&quot;)</value>
      <webElementGuid>4d2f85e2-4d5a-413e-9150-10442589f353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-4']</value>
      <webElementGuid>d93ec6b0-f17c-4e93-b862-2a19e56791f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-panel']/mat-option[2]</value>
      <webElementGuid>99b6dd68-8f02-4394-bfa4-ea1e797f18ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select a Site'])[1]/following::mat-option[1]</value>
      <webElementGuid>c11cd95e-6294-4fc3-856f-957fbb581c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K5 Sewing Plant'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>98fabf72-bf56-41ae-89e0-f6ee74a9e3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]</value>
      <webElementGuid>227b1a18-faec-4b17-9220-7f86a130fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-4' and (text() = 'K2 Sewing Plant' or . = 'K2 Sewing Plant')]</value>
      <webElementGuid>ac6791ee-609e-4d41-82f4-aba4fca539a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
