<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Site</name>
   <tag></tag>
   <elementGuidId>4817d990-eabb-4b63-bfcf-ee77a0c3e37a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='Site']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.s-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>1265bb2f-fc60-47c0-afcf-1663f675f773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-label</value>
      <webElementGuid>b528eae7-d160-4f3b-bad9-d7d305f8bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Site</value>
      <webElementGuid>0c4e8b70-9837-45bf-b4e2-7499fbe8b4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/main-layout[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container mat-drawer-transition&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content&quot;]/content[1]/div[@class=&quot;content&quot;]/home[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-mdc-card mdc-card&quot;]/mat-card-content[@class=&quot;mat-mdc-card-content&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;flex-container md-w-50&quot;]/div[@class=&quot;md-flex-row-basis&quot;]/div[1]/mat-label[@class=&quot;s-label&quot;]</value>
      <webElementGuid>3a57908c-5df6-4263-bc5f-0375c2c5ee14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Back!'])[1]/following::mat-label[1]</value>
      <webElementGuid>091fc7f7-ebfb-47a6-9c9a-767b6aae8e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dinithi Anupama |'])[1]/following::mat-label[1]</value>
      <webElementGuid>b69326fe-b540-4d50-ba27-1336ec2e3b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K2 Sewing Plant'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>6ce58ec9-63af-4159-9cbc-77bcb65f5e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>f966b5bc-eac3-467a-ad5f-ed8c77416628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Site']/parent::*</value>
      <webElementGuid>abef5632-4e54-4706-9c3a-f3e4f0ae9ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-label</value>
      <webElementGuid>dfd45074-51e1-451b-846b-424f6429b8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Site' or . = 'Site')]</value>
      <webElementGuid>972801fa-fb85-4a00-be83-06b099bb626b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
